### ISSUE TITLE
Feature Request: Have an option to disable the pmpromh_template_redirect_homepage

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-member-homepages#1]
When setting a memberships home page to the PMPro Account page, you are unable to access the sites front page (i.e. site.com redirects to site.com/account) when logged in as a member.

**Comment by andrewlimaza** [comment]
It's a bit difficult to explain in wording to have an option to disable this redirect.

`Disable your site's default front page and use the homepage selected instead` ?

Something along these lines.

**Comment by physiostasis** [comment]
Any solution to this problem? I am facing the same issue.

**Comment by ronalfy** [comment]
Notes: 

1. What’s happening here is if you wanted to redirect on login, there was a good TML module for that.

2. And our Member Homepages add on was for the use case where you WANT to redirect users away from the homepage somewhere else.

3. So people are using our Member Homepages plugin for the login redirect but don’t want the homepage redirect.

4. Just some background. We should still help with this usecase to make it easier for people to set up.

5. The big Q is just where to put the setting. Put it on advanced settings page? On the edit level page next to the homepage setting for each membership level? A different setting per level? (I think usually you want this on or off globally.)

6. I would avoid creating a separate settings page for the members homepage. But maybe we can/should and show the homepage for all levels.

**Comment by ronalfy** [comment]
@andrewlimaza @ideadude I think it would be easiest to place the option on the Membership Homepages settings page, and have a per-level override.

**Comment by andrewlimaza** [comment]
@ronalfy here's a gist to disable the replacement for now - https://gist.github.com/andrewlimaza/5c526c1c815c5d01e42f71b9da2bdc98

**Comment by ronalfy** [comment]
Notes from today's meeting. 

1. General consensus is to have a heading for Membership Homepages on the levels settings page.
2. Checkbox or option to disable the homepage redirect per level.
3. Detect Gist and provide warning if active.

An advanced global option is not recommended since it may lead to more support load, but then the user could just use the Gist for that.
