### ISSUE TITLE
Elementor - some pages cannot be edited

### ISSUE THREAD

**Issue by starship-gitter** [strangerstudios/pmpro-member-homepages#2]
When using "Member Homepages Add On" , ver 0.1, some Wordpress pages cannot be edited with Elementor. 
Error message:
The Content Area Was Not Found in Your Page

WP 5.02
PMP 2.0.1
Theme WP Astra

![2019-01-07_1056](https://user-images.githubusercontent.com/46442459/50761537-f2273580-126a-11e9-8d7b-ebdfaba0a0e1.png)

**Comment by kimcoleman** [comment]
Please update to the latest version of Paid Memberships Pro and let us know if this is still an issue.

**Comment by starship-gitter** [comment]
Sorry, I stopped using PMP last year.
