### ISSUE TITLE
Feature request: Add support for Elementor

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-member-homepages#28]
**Is your feature request related to a problem? Please describe.**
Add support for Elementor (and possibly other editors).

**Describe the solution you'd like**
Add support for Elementor.

**Describe alternatives you've considered**
Elementor loads the frontend, so temporarily disabling the Member Homepages Add On to edit the home page and then reactivating it works. 

**Additional context**
This came up in ticket 469121:

> I am using Paid Memberships Pro and Elementor to operate my service.
> 
> I added the Plugin “Paid Memberships Pro – Member Homepages Add On” to set the Front page depended on the membership level.
> 
> However , after turning on this plugin , I could not edit my Front page by Elementor.
> I could the other pages , but could not only Front page.
> 
> I tried to clarify which plugin’s conflict of this issue and found this plugin seems to be the root cause of this issue.
> 
> Please check this video to check my demonstration.
> 
> https://vimeo.com/786430975
> 
> I don’t know this issue is on PMP side or Elementor side.

Andrew made a [PR](https://github.com/strangerstudios/pmpro-member-homepages/pull/30/) for this.

**Comment by kimwhite** [comment]
Use this recipe to fix https://gist.github.com/kimwhite/0bb3c891c6e953d9843523c2a1439923
